name: StaffChat
version: ${project.version}
main: com.exortions.staffchat.StaffChat
api-version: 1.16
authors: [ Exortions ]
description: StaffChat is a highly customizable, lightweight plugin that allows your server admins to talk in private.
commands:
  staffchat:
    description: Main command for the StaffChat plugin.
    aliases:
      - sc